---
title: "Homework Week 08"
format: html
---

### 1
```{r}
library(rethinking)

data(Monks)
dat <- Monks
rm(Monks)
```

```{r}
# dyad model
f_dyad <- alist(
  likeAB ~ binomial(3, pAB),
  likeBA ~ binomial(3, pBA),
  logit(pAB) <- a + T[D, 1],
  logit(pBA) <- a + T[D, 2],
  a ~ normal(0, 1),
  
  ## dyad effects - non-centered
  transpars> matrix[N_dyads, 2]:T <-
    compose_noncentered(rep_vector(sigma_T, 2), L_Rho_T, Z),
  matrix[2, N_dyads]:Z ~ normal(0, 1),
  cholesky_factor_corr[2]:L_Rho_T ~ lkj_corr_cholesky(2),
  sigma_T ~ exponential(1),
  
  ## compute correlation matrix for dyads
  gq> matrix[2, 2]:Rho_T <<- Chol_to_Corr(L_Rho_T)
)
```

```{r}
n_dyads <- nrow(dat)
monk_dat <- list(
  N_dyads = nrow(dat),
  D = dat$dyad_id,
  likeAB = dat$like_AB,
  likeBA = dat$like_BA
)
```

```{r}
m1 <- ulam(
  f_dyad, 
  data = monk_dat,
  chains = 4, cores = 8, iter = 2000)
```

```{r}
precis(m1, depth = 3, pars = c("Rho_T", "sigma_T"))
```

```{r}
# dyad model with dislike
f_dyad2 <- alist(
  likeAB ~ binomial( 3 , pAB ),
  likeBA ~ binomial( 3 , pBA ),
  logit(pAB) <- a[1] + T[D,1] ,
  logit(pBA) <- a[1] + T[D,2] ,
  
  dislikeAB ~ binomial( 3 , qAB ),
  dislikeBA ~ binomial( 3 , qBA ),
  logit(qAB) <- a[2] + T2[D,1] ,
  logit(qBA) <- a[2] + T2[D,2] ,
  vector[2]:a ~ normal(0,1),
  
  ## like dyad effects - non-centered
  transpars> matrix[N_dyads,2]:T <-
    compose_noncentered( rep_vector(sigma_T,2) , L_Rho_T , Z ),
  matrix[2,N_dyads]:Z ~ normal( 0 , 1 ),
  cholesky_factor_corr[2]:L_Rho_T ~ lkj_corr_cholesky( 2 ),
  sigma_T ~ exponential(1),
  
  ## dislike dyad effects - non-centered
  transpars> matrix[N_dyads,2]:T2 <-
    compose_noncentered( rep_vector(sigma_T2,2) , L_Rho_T2 , Z2 ),
  matrix[2,N_dyads]:Z2 ~ normal( 0 , 1 ),
  cholesky_factor_corr[2]:L_Rho_T2 ~ lkj_corr_cholesky( 2 ),
  sigma_T2 ~ exponential(1),
  
  ## compute correlation matrix for dyads
  gq> matrix[2,2]:Rho_T <<- Chol_to_Corr( L_Rho_T ),
  gq> matrix[2,2]:Rho_T2 <<- Chol_to_Corr( L_Rho_T2 )
)

n_dyads <- nrow(dat)
monk_dat <- list(
  N_dyads = nrow(dat),
  D = dat$dyad_id,
  likeAB = dat$like_AB,
  likeBA = dat$like_BA,
  dislikeAB = dat$dislike_AB,
  dislikeBA = dat$dislike_BA )

m2 <- ulam( f_dyad2 , data=monk_dat , chains=4 , cores=4 , iter=2000 )
```

```{r}
precis(m2, depth = 3, pars = c("Rho_T", "Rho_T2"))
```

```{r}
post <- extract.samples(m2)
round(quantile(post$Rho_T[, 1, 2] - post$Rho_T2[, 1, 2]), 2)
```

